// Creates a single Google Calendar event with a Meet conference for a course
// session — the "add a one-off session" path. Recurring Sunday classes are
// generated by sunday-sessions-ensure instead.
//
// Deploy: supabase functions deploy google-meet-create
//
// The instructor's Google refresh token is stored in google_oauth_tokens by
// the google-oauth-store function after they sign in with the calendar scope.

import { json, preflight } from '../_shared/cors.ts';
import { requireUser, serviceClient } from '../_shared/supabase.ts';
import { courseAttendees, courseStudentIds, createMeetEvent, freshAccessToken } from '../_shared/google.ts';

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return preflight();

  try {
    const user = await requireUser(req);
    const { courseId, title, description, startsAt, endsAt, kind } = await req.json();
    if (!courseId || !title || !startsAt || !endsAt) return json({ error: 'Missing session details.' }, 400);

    const sessionKind = kind === 'doubt' ? 'doubt' : 'class';

    const db = serviceClient();

    const { data: course, error: courseError } = await db
      .from('courses')
      .select('id, title, instructor_id')
      .eq('id', courseId)
      .maybeSingle();
    if (courseError) throw courseError;
    if (!course) return json({ error: 'Course not found.' }, 404);
    if (course.instructor_id !== user.id) {
      return json({ error: 'Only the course instructor can schedule sessions.' }, 403);
    }

    const accessToken = await freshAccessToken(db, user.id);
    const attendees = await courseAttendees(db, courseId);

    const event = await createMeetEvent(accessToken, {
      summary: title,
      description: description || `Skillvo ${sessionKind === 'doubt' ? 'doubt session' : 'live session'} for "${course.title}"`,
      startsAt,
      endsAt,
      attendees,
    });

    const { data: session, error: insertError } = await db
      .from('live_sessions')
      .insert({
        course_id: courseId,
        instructor_id: user.id,
        kind: sessionKind,
        title,
        description: description ?? '',
        meet_url: event.meetUrl,
        google_event_id: event.eventId,
        starts_at: startsAt,
        ends_at: endsAt,
      })
      .select('*')
      .single();
    if (insertError) throw insertError;

    const studentIds = await courseStudentIds(db, courseId);
    if (studentIds.length) {
      const label = sessionKind === 'doubt' ? 'Doubt session' : 'Live session';
      await db.from('notifications').insert(
        studentIds.map((studentId) => ({
          user_id: studentId,
          type: 'session_scheduled',
          message: `📅 ${label} scheduled for "${course.title}": ${title}`,
          metadata: { course_id: courseId, session_id: session.id, meet_url: event.meetUrl, kind: sessionKind },
        })),
      );
    }

    return json(session);
  } catch (err) {
    if (err instanceof Response) {
      const reason = await err.clone().text().catch(() => '');
      return json({ error: reason || 'Unauthorized' }, err.status);
    }
    console.error(err);
    return json({ error: 'Could not create the Google Meet session.' }, 500);
  }
});
